allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  canvas: set this to true or false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
