import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import ts from 'typescript';
const source=fs.readFileSync('components/finanzas/OperatorCosts.tsx','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
const module={exports:{} as any};const require=createRequire(import.meta.url);
vm.runInNewContext(code,{module,exports:module.exports,Intl,Date,Set,Map,URLSearchParams,AbortController,require:(name:string)=>name.startsWith('./')?{__esModule:true,default:()=>null}:name==='@/lib/finanzas/operator-invoice-picker'?{}:require(name)});
const html=renderToStaticMarkup(React.createElement(module.exports.default));
assert.equal((html.match(/role="tab"/g)||[]).length,3);
assert.match(html,/id="tab-centros"[^>]*aria-selected="true"/);
assert.match(html,/role="tabpanel"/);
assert.doesNotMatch(html,/id="pending-refactoring-heading"|id="editor-heading"|id="sources-heading"/);
assert.match(html,/Coste propio/);assert.match(html,/Coste de terceros/);assert.match(html,/Total seleccionado/);
assert.match(source,/if \(next === tab\) return/);assert.match(source,/if \(id === grupoId\) return/);
assert.match(source,/OperatorCostDrawer/);assert.match(source,/tab === "propias" \? "PROPIA"/);
const drawer=fs.readFileSync('components/finanzas/OperatorCostDrawer.tsx','utf8');
assert.match(drawer,/showModal/);assert.match(drawer,/aria-modal="true"/);assert.match(drawer,/onCancel/);assert.match(drawer,/if \(busy\) return/);assert.match(drawer,/Descartar y cerrar/);
console.log('Pestañas: centros por defecto, tres vistas aisladas, sin formulario inline, navegación estable y panel modal protegido comprobados sin API/DB.');
